#!/bin/bash

directories_to_backup=(
    "/opt/"
    "/etc"
)
# Директория для хранения резервных копий
backup_dir="/backup"

current_date=$(date +'%Y-%m-%d')
for dir in "${directories_to_backup[@]}"; do
    dir_name=$(basename "$dir")
    backup_file="$backup_dir/${dir_name}_backup_$current_date.tar.gz"
    tar -czf "$backup_file" -C "$(dirname "$dir")" "$dir_name"
    echo "Создана резервная копия: $backup_file"
done
