#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Использование: $0 filename"
    exit 1
fi
filename=$1
if [ ! -f "$filename" ]; then
    echo "Файл $filename не найден."
    exit 1
fi

word_count=$(wc -w < "$filename")
echo "Количество слов в файле $filename: $word_count"
